### ISSUE TITLE
<640px

### ISSUE THREAD

**Issue by typomike** [cdaecke/md_fullcalendar#10]
Hi
is it possible in the next version to take into account in the css file that the display <640px has smaller buttons and a different arrangement?
![Uploading Bildschirmfoto 2021-08-04 um 14.34.53.png…]()

**Comment by typomike** [comment]
suggestion:

/* KALENDER */
@media screen and (max-width:640px) {
.fc-today-button,
.fc-button-group,
.fc-center
	{
		width: 50%;
		height: auto;
		font-size: 70%;
	}
.fc-today-button
	{
		margin-top: 10px;
	}
.fc-day-header,
.fc-axis
	{
		font-size: 70% !important;
	}
}
![Bildschirmfoto 2021-08-04 um 14 51 57](https://user-images.githubusercontent.com/3757657/128184083-7a8def99-107f-4d09-b309-198073170794.png)

**Comment by cdaecke** [comment]
All CSS regarding the calendar comes from [FullCalendar](https://fullcalendar.io/) itself.

You are free to overwrite styles in your own stylesheet or even create an own [Theme](https://fullcalendar.io/docs/theming).

Hope this helps!
