### ISSUE TITLE
problem with comments in Show.html when using a code-cleaner

### ISSUE THREAD

**Issue by michelrojahn** [cdaecke/md_fullcalendar#11]
Hey. I use your extension in a project that uses a code-cleaner. There are several comments with // instead of /* */. Because of the comments, the code is not processed correctly, which leads to a syntax error. After adjusting the comments, the code cleaner works too.

OT:
I'm not using Github often. Where can I send you feature-requests?

Thanks and greetings,
Michel

**Comment by cdaecke** [comment]
The template was adjusted and released with version 3 of the extension.
