### ISSUE TITLE
uncaught exception when there are ConfigurationGroups in calendarize

### ISSUE THREAD

**Issue by stefanhe** [cdaecke/md_fullcalendar#14]
When there are ConfigurationGroups besides Events in calendarize an uncaught exception will occur:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method HDNET\Calendarize\Domain\Model\ConfigurationGroup::getAbstract() | Error thrown in file /var/www/mywebserverdirectory/html/typo3conf/ext/md_fullcalendar/Classes/Controller/CalController.php in line 139. `

This is because there is no "getAbstract" method for a ConfigurationGroup, only for an Event.

My "very-quick-and-dirty" solution was to check if the object is an Event:

`103a104
>                 if (get_class($el->getOriginalObject()) !== "HDNET\Calendarize\Domain\Model\ConfigurationGroup") {
150a152
>               }
`

My versions:
typo3 10.4.23
calendarize 11.0.2
md_fullcalendar 2.0.3

**Comment by cdaecke** [comment]
Thanks for reporting!

I have just added a fix. Could you please double check, if this is working for you?

**Comment by cdaecke** [comment]
Version 3.0.0 was released, which solves this problem.
