### ISSUE TITLE
Template definitions in setup.typoscript

### ISSUE THREAD

**Issue by agendartobias** [cdaecke/md_fullcalendar#15]
view {
        templateRootPaths.0 = EXT:{extension.shortExtensionKey}/Resources/Private/Templates/
        templateRootPaths.1 = {$plugin.tx_mdfullcalendar_cal.view.templateRootPath}
        partialRootPaths.0 = EXT:md_fullcalendar/Resources/Private/Partials/
        partialRootPaths.1 = {$plugin.tx_mdfullcalendar_cal.view.partialRootPath}
        layoutRootPaths.0 = EXT:tx_mdfullcalendar/Resources/Private/Layouts/
        layoutRootPaths.1 = {$plugin.tx_mdfullcalendar_cal.view.layoutRootPath}
    }

I think this is a bug example: templateRootPaths.0 = EXT:{**extension.shortExtensionKey**}

**Comment by cdaecke** [comment]
Thanks for reporting. The paths are fixed with the attached commit. The changes will be available with the next release.
