### ISSUE TITLE
Bootstrap Modal View not displaying any content.

### ISSUE THREAD

**Issue by shortyxs** [cdaecke/md_fullcalendar#17]
Hello Chris (@cdaecke),
thank you for releasing this nice Typo3 extension.

However, I run into a problem that I can't fix.

We have set the UID for the Calendarize Storage and we have set the UID for the Page that contains the detail view.
When clicking on an event, the modal opens but does not show any content except the close button.

Can you give me any hint what is probably wrong?

Any help is much appreciated.

**Comment by shortyxs** [comment]
/typo3temp/var/log says
`Mon, 20 Jun 2022 20:22:38 +0200 [WARNING] request="bd1e06ca46c9f" component="TYPO3.CMS.Frontend.Controller.TypoScriptFrontendController": $TSFE->set_no_cache() was triggered. Reason: no_cache has been set before the page was generated - safety check. Caching is disabled!
`
The link prduced looks like `https://www.domain.de/sendeplan/sendeplan-einzelansicht/calendar-ajax.html?tx_mdfullcalendar_cal%5Baction%5D=detail&tx_mdfullcalendar_cal%5Bcontroller%5D=Cal&tx_mdfullcalendar_cal%5Bindex%5D=18764&cHash=d7dea49211c152930c8ce7771711da4e`
And gives back a white page.
The links should look like `https://www.domain.de/sendeplan/sendeplan-einzelansicht/termin/hit-factory-20220620`

I don't see any error messages appearing.

**Comment by cdaecke** [comment]
Try to remove the follwong routeEnhancer:

```yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      '/calendar-ajax.html': 1573760945
```

Flush the cache in the install tool an try again.

Is the link now correctly pointing to `https://www.domain.de/sendeplan/sendeplan-einzelansicht/termin/hit-factory-20220620`? If not, check, if `settings.pid.defaultDetailPid` is set to the page `hit-factory-20220620`.

**Comment by cdaecke** [comment]
Please flush the cache in the install tool and reload the page. After that, the link should not go to `.../calendar-ajax.html?...` any more.

The ajax call from the calendar, which opens the modal, gets the data from `ext:md_fullcalendar` (detailAction).

**Comment by cdaecke** [comment]
Is there already a preview of the website, so I could have a look and give some more advices?

**Comment by shortyxs** [comment]
https://test.radio-zoom.de/
On the start page you see a Calendarize List View, that links to the detailview.
And here https://test.radio-zoom.de/sendeplan You can see the fullcalendar, that should open the same detailview in the Modal.

I have removed any router enhancements. Cache was cleared.

I also Noticed, that when I now put pack int he
`routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      '/calendar-ajax.html': 1573760945`
Typo3 throws an error, not saying what is wrong, just the first line of my yaml config for calendar-ajax.

**Comment by cdaecke** [comment]
Could you please temporary add `\TYPO3\CMS\Core\Utility\DebugUtility::debug($index);` in the `detailAction()` of the `CalController`? Do you get any output when calling 
https://test.radio-zoom.de/sendeplan/sendeplan-einzelansicht?tx_mdfullcalendar_cal%5Baction%5D=detail&tx_mdfullcalendar_cal%5Bcontroller%5D=Cal&tx_mdfullcalendar_cal%5Bindex%5D=4696&type=1573760945&cHash=54411fcebbc2e9945baec2ccd030a41a

**Comment by shortyxs** [comment]
```
HDNET\Calendarize\Domain\Model\Indexprototypepersistent entity (uid=4696, pid=98)
   uniqueRegisterKey => protected'Event' (5 chars)
   foreignTable => protected'tx_calendarize_domain_model_event' (33 chars)
   foreignUid => protected9 (integer)
   startDate => protectedDateTimeprototypeobject (2022-06-29T02:00:00+02:00, 1656460800)
   endDate => protectedDateTimeprototypeobject (2022-06-29T02:00:00+02:00, 1656460800)
   startTime => protected25200 (integer)
   endTime => protected28800 (integer)
   allDay => protectedFALSE
   openEndTime => protectedFALSE
   state => protected'default' (7 chars)
   originalObject => protectedNULL
   slug => protected'die-mittwoch-morgaehn-meditation-20220629' (41 chars)
   uid => protected4696 (integer)
   _localizedUid => protected4696 (integer)modified
   _languageUid => protected0 (integer)modified
   _versionedUid => protected4696 (integer)modified
   pid => protected98 (integer)
```

**Comment by cdaecke** [comment]
Ok, data is available, at least in the controller.

Now add `<f:debug>{_all}</f:debug>` in `ext:md_fullcalendar/Resources/Private/Templates/Cal/Detail.html` right after `<f:section name="content">` (Line 8).

Call again https://test.radio-zoom.de/sendeplan/sendeplan-einzelansicht?tx_mdfullcalendar_cal%5Baction%5D=detail&tx_mdfullcalendar_cal%5Bcontroller%5D=Cal&tx_mdfullcalendar_cal%5Bindex%5D=4696&type=1573760945&cHash=54411fcebbc2e9945baec2ccd030a41a

Do you get an array with data for `settings` and `index`? If so, please check, if you have changed the path to the templates of `ext:md_fullcalendar`. If you use your own templates, please try using the originals and if that works, check your custom templates.

**Comment by shortyxs** [comment]
Yes I had changed the path with the templates, that is now reverted to the default.
I get the array when adding `<f:debug>{_all}</f:debug>` but still get an empty modal.

**Comment by shortyxs** [comment]
Even with this simplified Detailview I don't get any output
I added Some Fixed text to in the Header and even this is not rendered.

**Comment by shortyxs** [comment]
Thanks a lot. After the official reveal, I will setup a new dev instance of Typo3 and try to reproduce the problem.
