### ISSUE TITLE
No category colors

### ISSUE THREAD

**Issue by roblahnst** [cdaecke/md_fullcalendar#19]
Typo3 version is 10.4.21
calendarize 12.0
md_fullcalendar 3.01

I use categories, but the color of the events (background and bullet) is always blue.

**Comment by cdaecke** [comment]
Good point, there is nothing about the colors in the documentation!

Just add the following to your stylesheet, whereas the number at the end of `.category123` is the id of the category:

    .tx-md-fullcalendar .category123 {
        color: #fff;
        background-color: red;
    }

**Comment by roblahnst** [comment]
Works very well. Thanks.
