### ISSUE TITLE
TypeError at list action

### ISSUE THREAD

**Issue by rteitge** [cdaecke/md_fullcalendar#20]
Hi,

I clicked on an event in month view, then it shows the following error:

```
DateTime::__construct() expects parameter 1 to be string, null given
in /var/www/html/web/typo3conf/ext/md_fullcalendar/Classes/Controller/CalController.php line 89
$selectedStart = new \DateTime(GeneralUtility::_GP('start'));
```

Is there something wrong with my configuration?

TYPO3 10.4.36
PHP 7.4
calendarize 12.4.4
md_fullcalendar 3.0.2

**Comment by cdaecke** [comment]
Is the initial calendar show?
Please check in the console of your browser, if the get variable `start` is set. The ajax request should look something like this:

`https://www.mydomain.com/index.php?id=90&type=1573738558&storage=15&start=2023-05-01T00%3A00%3A00%2B02%3A00&end=2023-06-05T00%3A00%3A00%2B02%3A00`

**Comment by rteitge** [comment]
Hi, yes the initial calendar is shown. Here is the information from developer console:

Übersicht
URL: https://www.domain.de/terminkalender/kalender-terminansicht/termin/slug-20230323?type=1573738558
Status: 500
Quelle: Netzwerk
Adresse: 127.0.0.1:443

Anfrage
:method: GET
:scheme: https
:authority: www.domain.de
:path: /terminkalender/kalender-terminansicht/termin/slug-20230323?type=1573738558
Cookie: Typo3InstallTool=hash
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Host: www.domain.de
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Accept-Language: de-DE,de;q=0.9
Referer: https://www.domain.de/terminkalender
Connection: keep-alive

Antwort
:status: 500
Date: Wed, 29 Mar 2023 06:16:45 GMT
Content-Type: text/html; charset=UTF-8
Server: nginx/1.20.1

Parameter der Abfragezeichenkette
type: 1573738558

These are the date options of the event:

![Bildschirm­foto 2023-03-29 um 08 23 50](https://user-images.githubusercontent.com/83205200/228444588-632adec0-7e72-477c-9a70-68d10d66b52d.png)

**Comment by cdaecke** [comment]
The described error has nothing to do with the detail view of an entry, rather than displaying all entries in the calendar.

Did you modify the templates of `ext:md_md_fullcalendar`, especially the template `Cal/Show.html`?

**Comment by rteitge** [comment]
Ah ok, that was my guess because the error appears after clicking the event link in month view.
No, there is no modified template. I've migrated from cal and T3 v7 to calendarize and T3 v10 (the limit of migration cal > calendarize is the reason for v10). And then I recognized your ext. Added it to my composer setup, added the statics and created a FE Plugin. There are some old cal templates but the typescript is deactivated so they shouldn't affect anything.

My setup for your extension:

```
plugin.tx_mdfullcalendar_cal {
    settings {
        pid.defaultDetailPid = {$cal_detail_pid} // pid for the detail view of current website
        showIcsIcalButton = 1
    }
    persistence {
        storagePid = {$cal_pid_list} // comma separated list of a global and a local storage pid
    }
}
```

**Comment by rteitge** [comment]
@cdaecke if you need some more information feel free to contact me at typo3 slack :-)

**Comment by rteitge** [comment]
The ajax request has the correct format with start parameter: https://www.my-domain.de/index.php?id=52106&type=1573738558&storage=&start=2023-03-27T00%3A00%3A00%2B02%3A00&end=2023-05-01T00%3A00%3A00%2B02%3A00

**Comment by rteitge** [comment]
And the error is shown when calling the site with the calendarize detail plugin:
https://www.my-domain.de/.../termin/termin-title-20230323?type=1573738558

Without the type parameter the site is shown correctly. I guess this parameter is responsible for calling the list action of md_fullcalendar.

**Comment by rteitge** [comment]
After some time of debugging it seems that the Typo3 UriBuilder/PageLinkBuilder sets the page type with the value of listAction 1573738558 if no page type != 0 is set like at urlajax.

**Comment by cdaecke** [comment]
Hm, I can't reproduce your issue.
Is the page with the problem online available, so I could have a look?

**Comment by rteitge** [comment]
Hi, unfortunatelly not. It's a developing instance in local ddev. How can I provide you some DebugUtility outputs if that helps?

**Comment by cdaecke** [comment]
With TYPO3 v12 I was now able to reproduce your error. I did some changes, also in order to make the extension compatible with TYPO3 v12.

Please check the current master, if this works for you.

**Comment by rteitge** [comment]
Hi, sorry for the late reply. I tested the current version 4.0.1 with v12 and it works now. Thank you very much!
