### ISSUE TITLE
TYPO3 v12

### ISSUE THREAD

**Issue by agendartobias** [cdaecke/md_fullcalendar#24]
Hey, is there going to be a release for TYPO3 v12?

**Comment by cdaecke** [comment]
Yes, this extension will be available for TYPO3 v12. Hopefully I will find time within the next weeks.

**Comment by cdaecke** [comment]
I have just pushed some changes, which add support for TYPO3 v12.

Could you please give it a try and check the current master?

**Comment by agendartobias** [comment]
It works, thank you. If i see some bug i will let you know.

Aditional question - it's more feature request than bug - when i click on some event in calendar it opens "modal box" can i change this somehow to get single view of event like in ext:calendarize?

**Comment by cdaecke** [comment]
> It works, thank you. If i see some bug i will let you know.

Thanks for your feedback!

> Aditional question - it's more feature request than bug - when i click on some event in calendar it opens "modal box" can i change this somehow to get single view of event like in ext:calendarize?

This works out of the box. Just copy the template `Show.html` to your own extension and remove the following code:
https://github.com/cdaecke/md_fullcalendar/blob/ebdfe88a1407d5692a257ec088943df8cdd2c7d3/Resources/Private/Templates/Cal/Show.html#L84-L101

**Comment by agendartobias** [comment]
Thank you. Have a great day!

**Comment by andreheuer** [comment]
Hi @cdaecke,
are you planning to "officially" release the v12 version soon?

**Comment by cdaecke** [comment]
Version 4.0.0 is released.
