### ISSUE TITLE
There was an error while fetching events!

### ISSUE THREAD

**Issue by Sana-Houcine** [cdaecke/md_fullcalendar#25]
Is the static TypoScript template FullCalendar.io for ext:Calendarize included and did you configure the defaultDetailPid?

[md_fullcalendar/Configuration/TypoScript/setup.typoscript](https://github.com/cdaecke/md_fullcalendar/blob/5138685e4d8fab83f6fea97d1f5e58ff0816023c/Configuration/TypoScript/setup.typoscript#L34)

Line 34 in [5138685](https://github.com/cdaecke/md_fullcalendar/commit/5138685e4d8fab83f6fea97d1f5e58ff0816023c)

 defaultDetailPid =
 i did all that but i got allaws the same error and it's impssible to see the events in the calendar i'm using typo3 v 11 
 i added it in the set up and in the constant in the back typo but nothing

**Comment by cdaecke** [comment]
Please open the developer tools in your browser and look for the ajax call in the network tab. You will find something like this:

`/index.php?id=89&type=1573738558&storage=90&start=2023-10-30T00%3A00%3A00%2B01%3A00&end=2023-12-04T00%3A00%3A00%2B01%3A00`

Open this request in a new browser window and post the error message here.

**Comment by Sana-Houcine** [comment]
http://localhost/index.php?id=2&type=1573738558&storage=26&start=2023-10-30T00%3A00%3A00%2B01%3A00&end=2023-12-04T00%3A00%3A00%2B01%3A00
this how it was in there with 302 as the status, when i try to open it it go directly to the welcome page of xampp dashboard

**Comment by Salim-Dziri-Imbus** [comment]
i have the same error
ajax call: http://localhost/index.php?id=8&type=1573738558&storage=12&start=2023-10-30T00%3A00%3A00%2B01%3A00&end=2023-12-04T00%3A00%3A00%2B01%3A00
result
![Screenshot from 2023-11-20 15-56-02](https://github.com/cdaecke/md_fullcalendar/assets/151547342/979e610a-007c-4ecb-a570-a123f6374370)

**Comment by cdaecke** [comment]
@Sana-Houcine @Salim-Dziri-Imbus What is the URL of your website?

I assume, that your Website is not running at `http://localhost/index.php`, so you have to copy the template `Show.html` to your "theme" extension and adjust the following line to your needs: 
https://github.com/cdaecke/md_fullcalendar/blob/ebdfe88a1407d5692a257ec088943df8cdd2c7d3/Resources/Private/Templates/Cal/Show.html#L56

If the value in `{sitePath}` is not correct, replace the variable with the needed path to your website.

**Comment by Sana-Houcine** [comment]
404
Page Not Found

The page did not exist or was inaccessible. Reason: The requested page does not exist
even when we adjust the url of our site its the same there is something wrong with the extension in typo v 11 that's for sure now but where it goes wrong i really don't know you must put some detailed demo for config especialy when there error repeated like this we aren't the first one to signal this type of error , i'm sad because i passed more then 2 days and still the same error

**Comment by Sana-Houcine** [comment]
![1](https://github.com/cdaecke/md_fullcalendar/assets/124881786/166dfbe5-70f3-40b4-aa7d-fa134a687534)
![screenfull cal](https://github.com/cdaecke/md_fullcalendar/assets/124881786/2c989304-abcb-41c5-af1d-0193e4be1d0f)

thank you for your answer , the extension is good and i like that's why i hope that it will work directly , i must mention that i'm new in typo3 so it's difficul to find all the set up and config , i need to thank a friend yesterday he helps me with your extension and it work now exactly as i wish, i'll join some screen shot for those who are new like my self if they have the same error as me 

we must to add this because of the cHash error after modifie the path of the url in show.html 
'FE' => [
        'cacheHash' => [
            'enforceValidation' => true,
        ],
        'debug' => false,
        'disableNoCacheParameter' => true,
        'pageNotFoundOnCHashError' => 0,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
LocalConfiguration.php
as will i included the extension of js library
https://extensions.typo3.org/extension/lib_jquery
you need as will to add this in your set up your extension y're working on 
plugin.tx_mdfullcalendar_cal {
    view {
        templateRootPath >
        templateRootPaths {
            10 = EXT:your_extension_name/Resources/Private/Templates/Extensions/md_fullcalendar/
        }
    }
}
@import 'EXT:your_extension_name/Configuration/TypoScript/Extensions/'
in the template include the order is important as will 
thank you!

**Comment by cdaecke** [comment]
@Sana-Houcine That sounds all very complicated. I am sure, you do not have to change settings in `LocalConfiguration.php`.

If you provide your local test URL, I am sure, that I can point you in the right direction.

**Comment by cdaecke** [comment]
@agendartobias Could you please add a detailed step by step info on how to reproduce this issue? Please tell me what you do and what you expect.

**Comment by agendartobias** [comment]
Ther's no specific step. I just have your plugin "FullCalendar for ext:calendarize" inserted on subpage and i get Javascript error message: "There was an error while fetching events!".

If i look XHR response/request i get: 404 Not Found. The url is: https://mydomain.eu/index.php?id=1&type=1573738558&storage=702&start=2024-01-29T00%3A00%3A00%2B01%3A00&end=2024-03-04T00%3A00%3A00%2B01%3A00

Query string parameters:

`
id: 1
type: 1573738558
storage: 702
start: 2024-01-29T00:00:00+01:00
end: 2024-03-04T00:00:00+01:00
`
As i said if i set the [FE][pageNotFoundOnCHashError] to false i get your calendar rendered on subpage with all the events.

**Comment by agendartobias** [comment]
No, still the same problem.

**Comment by cdaecke** [comment]
@agendartobias Do you use your own `Show.html` template? Have you cleared the TYPO3 cache?

**Comment by agendartobias** [comment]
Yes, i use own (local) show template but i change/added this line of code. Yes i cleared cache

**Comment by cdaecke** [comment]
@agendartobias Sorry, my fault. Give me some minutes...

**Comment by cdaecke** [comment]
@agendartobias Now it should work. Could you please give the current master a try again?

**Comment by agendartobias** [comment]
Now it works. Thank you!
