### ISSUE TITLE
Filtering calendar that utilizes +# for more than 2 items leaves an empty +#

### ISSUE THREAD

**Issue by dwangove** [cdaecke/md_fullcalendar#3]
When a day has more that 2 items and those items are removed via filtering, an empty link showing the +# is still present and active.
https://www.reachhighermontana.org/stay-informed/calendar "filter for conferences"

**Comment by cdaecke** [comment]
Thanks for reporting!

The attached change in the template `Show.html` should address and fix this problem.

**Comment by cdaecke** [comment]
fixed in version 1.1.1 of the extension
