### ISSUE TITLE
Error while fetching events

### ISSUE THREAD

**Issue by hweckhardt** [cdaecke/md_fullcalendar#5]
I am using Typ3 10.4.6, calendarize 7.0.0 and md_fullcalendar 2.0.1.

When I open the Fullcalendar, i get these errors:

There was an error while fetching events! (popup window in browser)

And in the Typo3 backend:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder::setTargetPageUid() must be of the type integer, string given, called in /html/typo3/typo3conf/ext/md_fullcalendar/Classes/Controller/CalController.php on line 108 | TypeError thrown in file /html/typo3/typo3_src-10.4.6/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php in line 454. Requested URL: https://clubxy.de/index.php?id=428&type=1573738558&storage=467&start=2020-08-31T00%%3A00%%3A00%%2B02%%3A00&end=2020-10-05T00%%3A00%%3A00%%2B02%%3A00

This error is new.

**Comment by cdaecke** [comment]
Is the static TypoScript template `FullCalendar.io for ext:Calendarize` included and did you configure the `defaultDetailPid`? https://github.com/cdaecke/md_fullcalendar/blob/5138685e4d8fab83f6fea97d1f5e58ff0816023c/Configuration/TypoScript/setup.typoscript#L34

**Comment by hweckhardt** [comment]
Many thanks for the fast answer.

 

Yes, I only had configured the storage page (with the constants editor). After configuring the defaultDetailPid (in setup.typoscript) it works perfect. Many thanks again!

 

 

Von: chris [mailto:notifications@github.com] 
Gesendet: Montag, 7. September 2020 21:35
An: cdaecke/md_fullcalendar
Cc: hweckhardt; Author
Betreff: Re: [cdaecke/md_fullcalendar] Error while fetching events (#5)

 

Is the static TypoScript template FullCalendar.io for ext:Calendarize included and did you configure the defaultDetailPid? https://github.com/cdaecke/md_fullcalendar/blob/5138685e4d8fab83f6fea97d1f5e58ff0816023c/Configuration/TypoScript/setup.typoscript#L34
