### ISSUE TITLE
Error while fetching events!

### ISSUE THREAD

**Issue by ThomasRathje** [cdaecke/md_fullcalendar#7]
I am using Typo3 10.4.12, calendarize 8.0.0 and md_fullcalendar 2.0.1. PHP 7.3.23 FASTCGI
The TYPO3 is installed without Composer.
When I open the Fullcalendar, i get these errors:
There was an error while fetching events! (popup window in browser)
In the backend Logfile:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to HDNET\Calendarize\Domain\Repository\IndexRepository::findByTimeSlot() must implement interface DateTimeInterface or be null, int given, called in /kunden/147222_73765/rp-hosting/4470/5470/typo3cms/kirche-kellinghusen-10lts/typo3conf/ext/md_fullcalendar/Classes/Controller/CalController.php on line 101 | TypeError thrown in file /kunden/147222_73765/rp-hosting/4470/5470/typo3cms/kirche-kellinghusen-10lts/typo3conf/ext/calendarize/Classes/Domain/Repository/IndexRepository.php in line 527. Requested URL: http://work.kirche-kellinghusen.de/index.php?id=177&type=1573738558&storage=135&start=2020-12-28T00%%3A00%%3A00%%2B01%%3A00&end=2021-02-01T00%%3A00%%3A00%%2B01%%3A00

Plugin calendarize runs without error. On same page are the plugin md_fullcalendar.
StoragePid and defaultDetailPid are set. Static Template are integrated.
RouteEnhancers are registered. Same installation runs with TYPO3 9LTS.
Can someone help me please?

**Comment by cdaecke** [comment]
I did not test with ext:calendarize v 8.0.0 so far but it should work with version 7.3.0 of ext:calendarize.

**Comment by ThomasRathje** [comment]
Thank you, it does.

**Comment by cdaecke** [comment]
Version 2.0.2 was just released. This supports ext:calendarize >= v8.
