### ISSUE TITLE
compatibility with calendarize 8.x / 9.x

### ISSUE THREAD

**Issue by kweidler** [cdaecke/md_fullcalendar#8]
Are there plans to make the extension compatible with calendarize 8.x / 9.x?
Many thanks for your work!

error TYPO3 10.4.14, calenderize 9.0, md_fullcalendar 2.0.1
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to HDNET\Calendarize\Domain\Repository\IndexRepository::findByTimeSlot() must implement interface DateTimeInterface or be null, int given, called in /typo3conf/ext/md_fullcalendar/Classes/Controller/CalController.php on line 101 | TypeError thrown in file /typo3conf/ext/calendarize/Classes/Domain/Repository/IndexRepository.php in line 532.

**Comment by cdaecke** [comment]
Version 2.0.2 was just released. This supports `ext:calendarize` >= v8.
