### ISSUE TITLE
Error while fetching events!

### ISSUE THREAD

**Issue by dwangove** [cdaecke/md_fullcalendar#9]
10.4.12 / Calendarize 9.0 / MD 2.02
This is the same error as another reported issue in relation to Calendarize 8, and the subsequent 2.0.2 release.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder::setTargetPageUid() must be of the type int, string given, called in /opt/typo3-10.4.9-0/apps/typo3/htdocs/public/typo3conf/ext/md_fullcalendar/Classes/Controller/CalController.php on line 106 \| TypeError thrown in file /opt/typo3-10.4.9-0/apps/typo3/htdocs/public/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php in line 454.

**Comment by cdaecke** [comment]
Did you check the solution in #5?

**Comment by dwangove** [comment]
Yes, I had done those, but had forgotten to clear the caches thereafter. Thanks!

 

I also took the time to expose those settings via ‘constants editor’, rather than manual editing of the files.

You might add them to your extension in future releases, my guess it would alleviate many issues for users.

 

In setup:

    settings {

        dateFormat = {$plugin.tx_mdfullcalendar_cal.settings.dateFormat}

        timeFormat = {$plugin.tx_mdfullcalendar_cal.settings.timeFormat}

 

        pid {

            defaultDetailPid = {$plugin.tx_mdfullcalendar_cal.settings.defaultDetailPid}

        }

 

        # if you enable this, make sure that you have set "defaultDetailPid" and there is a

        # ext:calendarize plugin inserted on that page.

        showIcsIcalButton = {$plugin.tx_mdfullcalendar_cal.settings.showIcsIcalButton}

    }

 

In constants: (after persistence)

 

settings {

        # cat=plugin.tx_mdfullcalendar_cal//a; type=string; label=Date Format

        dateFormat = d.m.Y

        # cat=plugin.tx_mdfullcalendar_cal//a; type=string; label=Time Format

        timeFormat = H:i

        # cat=plugin.tx_mdfullcalendar_cal//a; type=string; label=Default Detail PID

        defaultDetailPid =

        # cat=plugin.tx_mdfullcalendar_cal//a; type=string; label=Show ICS/ICAL Button

        showIcsIcalButton = 0

    }

 

Regards,

Dave
